apiVersion: v1
kind: Service
metadata:
  name: machine-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: machine-controller-manager
spec:
  ipFamily: IPv4
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.metricsPort }}
    protocol: TCP
  selector:
    app: kubernetes
    role: machine-controller-manager