apiVersion: v1
kind: Service
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: cloud-controller-manager
spec:
  ipFamily: IPv6
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ include "cloud-controller-manager.port" . }}
      protocol: TCP
  selector:
    app: kubernetes
    role: cloud-controller-manager