machineClasses:
- name: class-1
# labels:
#   foo: bar
  region: europe-1
  availabilityZone: europe-1a
  machineType: medium_2_4
  keyName: my-ssh-key
  imageName: coreos-v1.0
  #imageID: 836428cd-5f98-1305-af9d-9825d4dfd0ec
  networkID: 426428cd-5e88-4005-9fad-9555d4dfd0fb
  networkIDv6: 426428cd-5e88-4005-9fad-9555d4dfd0fb
  podNetworkCidr: 100.96.0.0/11
  # rootDiskSize: 100 # 100GB
  # volumeType: openstackVolumeType
  # serverGroupID: b35e94c1-15a7-4b54-a0f6-8789fasdf79s
  securityGroups:
  - my-security-group
  tags:
    kubernetes.io/cluster/shoot-crazy-botany: "1"
    kubernetes.io/role/node: "1"
  secret:
    authURL: ABCD
    domainName: ABCD
    tenantName: abc
    username: abc
    password: abc
    cloudConfig: abc
  credentialsSecretRef:
    name: cloudprovider
    namespace: shoot-namespace