{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.labels }}
  labels:
{{ toYaml $machineClass.labels | indent 4 }}
{{- end }}
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
  authURL: {{ $machineClass.secret.authURL | b64enc }}
  insecure: dHJ1ZQ== # true
  domainName: {{ $machineClass.secret.domainName | b64enc }}
  tenantName: {{ $machineClass.secret.tenantName | b64enc }}
  username: {{ $machineClass.secret.username | b64enc }}
  password: {{ $machineClass.secret.password | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: OpenStackMachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  region: {{ $machineClass.region }}
  availabilityZone: {{ $machineClass.availabilityZone }}
  flavorName: {{ $machineClass.machineType }}
  keyName: {{ $machineClass.keyName }}
{{- if $machineClass.imageID }}
  imageID: {{ $machineClass.imageID }}
{{- else }}
  imageName: {{ $machineClass.imageName }}
{{- end }}
  networkID: {{ $machineClass.networkID }}
  networkIDv6: {{ $machineClass.networkIDv6 }}
  podNetworkCidr: {{ $machineClass.podNetworkCidr }}
{{- if $machineClass.rootDiskSize }}
  rootDiskSize: {{ $machineClass.rootDiskSize }}
{{- end}}
{{- if $machineClass.volumeType }}
  volumeType: {{ $machineClass.volumeType }}
{{- end}}
  securityGroups:
{{ toYaml $machineClass.securityGroups | indent 2 }}
  secretRef:
    name: {{ $machineClass.name }}
    namespace: {{ $.Release.Namespace }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
{{- end }}
