replicas: 1
clusterName: shoot-foo-bar
kubernetesVersion: 1.7.5
podNetwork: 192.168.0.0/16
podAnnotations: {}
podLabels: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
proxy: {}
#  http_proxy: "mytest.proxy:8118"
#  no_proxy: "192.168.0.0/24"
images:
  hyperkube: image-repository:image-tag
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi
