apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: extensions.gardener.cloud:yawol-controller
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["yawol.stackit.cloud"]
    resources:
    - "loadbalancersets"
    - "loadbalancersets/status"
    - "loadbalancermachines"
    - "loadbalancermachines/status"
    - "loadbalancers"
    - "loadbalancers/status"
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - "secrets"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups: [""]
    resources:
      - "serviceaccounts"
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - "roles"
      - "rolebindings"
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - "events"
    verbs: ["create"]
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extensions.gardener.cloud:yawol-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extensions.gardener.cloud:yawol-controller
subjects:
  - kind: ServiceAccount
    name: yawol-controller
    namespace: {{ .Release.Namespace }}