apiVersion: v1
kind: Service
metadata:
  name: yawol-cloud-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: yawol-cloud-controller
spec:
  ipFamily: IPv6
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
  selector:
    app: kubernetes
    role: yawol-cloud-controller