apiVersion: v1
kind: Service
metadata:
  name: yawol-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: yawol-controller
spec:
  ipFamily: IPv4
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      protocol: TCP

  selector:
    app: kubernetes
    role: yawol-controller